apiVersion: v1
kind: Service
metadata:
  name: java-tomcat-app
  labels:
    app: java-tomcat-app
spec:
  type: NodePort  # Use LoadBalancer if deploying on cloud infrastructure
  ports:
    - port: 8080
      targetPort: 8080
      nodePort:  30411
      protocol: TCP
  selector:
    app: java-tomcat-app
